database:
  adapter: mysql2
  database: <%= ENV['DB_COLON_FILES_DATABASE'] %>
  username: <%= ENV['DB_COLON_FILES_USERNAME'] %>
  password: <%= ENV['DB_COLON_FILES_PASSWORD'] %>
  host: db
  encoding: utf8
  pool: 5
solutions:
  path: /data/colon-files/uploads/solutions/
tasks:
  path: /data/colon-files/uploads/tasks/
